### ISSUE TITLE
ignoreForTagNames should include all form controls that accept keyboard input

### ISSUE THREAD

**Issue by DanielHeath** [dddice/react-keybind#573]
In particular, `textarea` is not an `input` but acts like one, and `select` tags use keyboard input to jump to an `option`.

**Comment by tlackemann** [comment]
Thanks for raising an issue @DanielHeath !

You should be able to pass in the `ignoreTagNames` prop to ignore the suggested elements.

```typescript
<ShortcutProvider ignoreTagNames={['input', 'textarea', 'select']}>
</ShortcutProvider>
```

That said I'm open to considering changing the default as right now it is only `input`.

**Comment by tlackemann** [comment]
I thought this over and agree that including the default form element types to the ignore list is beneficial. Appreciate your suggestion here.

This will be released in the next minor version.
